apiVersion: v1
kind: ConfigMap
metadata:
  name: app-cm
  namespace: go-k8s-demo
data:
  DB_HOST: "postgres-service"           # Name of service (refer db/service.yml)
  DB_USERNAME: "**********"             # Database Username
  DB_PASSWORD: "*********"              # Database Password
  DB_NAME: "**********"                 # Database Name
  DB_PORT: "*********"                  # Database Port
