apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-k8s-demo-deploy
  namespace: go-k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-k8s-demo-app
  template:
    metadata:
      labels:
        app: go-k8s-demo-app
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - image: mukulmantosh/go_k8s:1.0
          imagePullPolicy: Always
          name: go-k8s-demo
          envFrom:
            - configMapRef:
                name: app-cm
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/data/db"
              name: postgres-storage