apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: go-k8s-demo
  labels:
    app: app-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004
  selector:
    app: go-k8s-demo-app