@URL=http://localhost:8080
// @URL=http://localhost:30004 <- Uncomment once app is live on K8s.


### Create a new user
POST {{URL}}/user
Content-Type: application/json

{
  "name": "John Wick",
  "age": 44,
  "email": "johnwick@gmail.com"
}



### GET Users List
GET {{URL}}/users
Accept: application/json



### Update User by ID
// change user id
@userid = 2
PUT {{URL}}/user/{{userid}}
Content-Type: application/json

{
  "name": "John Wick 2",
  "age": 54,
  "email": "johnwick22@gmail.com"
}

### Delete User by ID

DELETE {{URL}}/user/{{userid}}
Content-Type: application/json
